{% set name = "dials-dependencies" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3461e77a2b3456febe5362d281199d2e68c8e00702159e770ecede272ab5dde

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-blosc >=1.8
    - jinja2
    - mock >=2.0
    - msgpack-c
    - msgpack-python
    - networkx
    - orderedset
    - procrunner >=0.6
    - pytest >=3.6,<5.0
    - scikit-learn <0.21
    - scipy
    - six
    - tqdm =4.23.4

test:
  imports:
    - dials_dependencies
  requires:
    - pytest
  commands:
    - py.test --pyargs dials_dependencies

about:
  home: https://dials.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Conda-package describing DIALS dependencies'

  description: |
    DIALS <https://dials.github.io> is the Diffraction Integration for
    Advanced Light Sources package, used to integrate crystallographic data.
    It has a large set of complex dependencies and currently can not be easily
    installed via pip or conda. This package aims to make the installation
    process less cumbersome.
  dev_url: https://github.com/dials/dials-dependencies

extra:
  recipe-maintainers:
    - anthchirp
